name: Test apps/deno
on:
  push:
    paths:
      - "apps/deno/**"
jobs:
  test-deno:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/deno
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - run: deno fmt --check
      - run: deno test
